# Generated by Django 5.1.7 on 2025-03-15 13:58

import prescription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalprescription",
            name="file",
        ),
        migrations.AddField(
            model_name="medicalprescription",
            name="prescription_file",
            field=models.FileField(
                default=None, upload_to=prescription.models.prescription_upload_path
            ),
        ),
    ]
